name: Analyse code

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_code:
    name: Run code analyser
    uses: ehennestad/matbox-actions/.github/workflows/check-code-workflow.yml@v1
    with:
      source_directory: code
      tools_directory: tools
