name: Run Codespell
# NB: Will only process "skip" and "ignore-words-list" from the codespell 
# config file if provided

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-codespell:
    name: Run Codespell
    uses: ehennestad/matbox-actions/.github/workflows/codespell-workflow.yml@v1
    with:
      config_file: tools/.codespellrc
