name: Test code

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*md'
      - '.github/**'

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*md'
      - '.github/**'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-code:
    name: Analyse and test code
    uses: ehennestad/matbox-actions/.github/workflows/test-code-workflow.yml@v1
    with:
      source_directory: code
      tools_directory: tools
      tests_directory: tools/tests

      # Name of MATLAB Release to use for running test suites and code analysis
      matlab_release: latest

      # Whether to cache the MATLAB installation for faster subsequent setups
      matlab_use_cache: true
